
=head1 NAME

Mojolicious::Guides - Mojolicious Guide To The Galaxy

=head1 DON'T PANIC!

These guides are currently being written, to get status updates and/or read
early drafts you can visit L<http://kraih.com>, L<http://twitter.com/kraih>
and L<http://github.com/kraih/mojo> or join the official IRC channel C<#mojo>
on C<irc.perl.org>.

=head1 TUTORIAL

A really fast and fun way to get started developing web applications with
Mojolicious is the tutorial in L<Mojolicious::Lite>, you should take a look.

=head1 GUIDES

New guides will be added over time, so keep a close eye on this.

=over 4

=item L<Mojolicious::Guides::Routing>

Simple and fun introduction to the L<Mojolicious> router.

=item L<Mojolicious::Guides::Rendering>

Generating content with the L<Mojolicious> renderer.

=item L<Mojolicious::Guides::Cookbook>

Cooking with L<Mojolicious>, recipes for every taste.

=item L<Mojolicious::Guides::Cheatsheet>

A concise all-purpose reference.

=item L<Mojolicious::Guides::FAQ>

Frequently asked questions with the right answers.

=item L<Mojolicious::Guides::CodingGuidelines>

Coding guidelines and mission statement.
A must read for developers and contributors!

=back

=head1 MORE

A lot more documentation and examples by many different authors can be found
in the Mojolicious wiki at L<http://github.com/kraih/mojo/wiki>.

=cut
