# Copyright (C) 2008, Sebastian Riedel.

=head1 NAME

Mojo::Manual::GettingStarted - Getting Started

=head1 OVERVIEW

This was supposed to be written as part of a Perl Foundation grant,
sadly the Perl Foundation didn't have the money to sponsor it.

=head1 FIRST STEPS

*** These are just a few pointers in the right direction in case someone is
insane enough to beta test Mojo. :) ***

Use the application generator to create all neccessary files.

    mojo generate app MyFirstApp

Thats it, you have just created your very first Mojo application.
Now it's time to start the built in server.

    cd my_first_app
    bin/my_first_app daemon

You can visit your application at http://127.0.0.1:3000.
Testing is just as simple.

    bin/my_first_app test

There are many more helpful scripts, and mojo will list them for you.

    bin/my_first_app

Have fun!

=cut