#!/usr/bin/env perl

# Copyright (C) 2008-2010, Sebastian Riedel.

use strict;
use warnings;

use Cwd 'getcwd';
use File::Spec;
use FindBin;

use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/../lib";

my $home;

BEGIN {
    $home = $ENV{MOJO_HOME};
    $home = join '/', File::Spec->splitdir($home ? $home : getcwd), 'lib';
}
use lib $home;

# Check if Mojo is installed
eval 'use Mojolicious::Commands';
die <<EOF if $@;
It looks like you don't have the Mojo Framework installed.
Please visit http://mojolicious.org for detailed installation instructions.

EOF

# Start the command system
Mojolicious::Commands->start;

__END__

=head1 NAME

mojolicious - The Mojolicious Command System

=head1 SEE ALSO

L<Mojolicious>, L<Mojolicious::Guides>, L<http://mojolicious.org>.

=cut
